services:
  - type: web
    name: telegram-helper-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt  # <-- убрали 'bot/'
    startCommand: python bot/bot.py
    envVars:
      - key: TG_HELPER_BOT_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
